project:
  type: website
  output-dir: docs

editor:
  render-on-save: true
  
website:
  title: "Hawkinslab"
  page-navigation: false
  site-url: https://hawkins-tech-lab.github.io/
  description: "TECH lab website"
  navbar:
    search: true
    title: false
    logo: assets/images/logo_tech.png
    logo-alt: "TECH Group"
    left:
      - text: "Team"
        href: team/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Teaching"
        menu:
          - text: "CIVE461/861"
            href: teaching/CIVE461/index.qmd
          - text: "ENCI707"
            href: teaching/ENCI707/index.qmd
          - text: "CIVE990T"
            href: teaching/Guest Lectures/CIVE990T.qmd
      - text: Thoughts
        menu:
          - text: "Books"
            href:  thoughts/books.qmd
          - text: "Blog"
            href:  thoughts/blog.qmd
    right:
      - icon: rss
        href: index.xml
    background: "#595758"
    
  sidebar:

    - id: CIVE461
      title: "CIVE 461"
      background: "#95B0B7"
      logo: "assets/images/teaching/cive_461_logo.png"
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: teaching/CIVE461/course-overview.qmd
              text: Overview
            - href: teaching/CIVE461/course-syllabus.qmd
              text: Syllabus
            - href: teaching/CIVE461/course-team.qmd
              text: "Teaching team"
            - href: teaching/CIVE461/index.qmd
              text: Schedule
            - href: teaching/CIVE461/course-faq.qmd
              text: FAQ
        - section: "Computing"
          contents:
            - href: teaching/CIVE461/computing/computing-access.qmd
              text: "Access"
            - href: teaching/CIVE461/computing/computing-troubleshooting.qmd
              text: "Troubleshooting"
        - section: "Weekly Materials"
          contents:
            - href: teaching/CIVE461/weeks/week-1.qmd
              text: "Week 1"
            - href: teaching/CIVE461/weeks/week-2.qmd
              text: "Week 2"
            - href: teaching/CIVE461/weeks/week-3.qmd
              text: "Week 3"
            - href: teaching/CIVE461/weeks/week-4.qmd
              text: "Week 4"
            - href: teaching/CIVE461/weeks/week-5.qmd
              text: "Week 5"
            - href: teaching/CIVE461/weeks/week-6.qmd
              text: "Week 6"
            - href: teaching/CIVE461/weeks/week-7.qmd
              text: "Week 7"
            - href: teaching/CIVE461/weeks/week-8.qmd
              text: "Week 8"
            - href: teaching/CIVE461/weeks/week-9.qmd
              text: "Week 9"
            - href: teaching/CIVE461/weeks/week-10.qmd
              text: "Week 10"
            - href: teaching/CIVE461/weeks/week-11.qmd
              text: "Week 11"
            - href: teaching/CIVE461/weeks/week-12.qmd
              text: "Week 12"
            - href: teaching/CIVE461/weeks/week-13.qmd
              text: "Week 13"
            - href: teaching/CIVE461/weeks/week-14.qmd
              text: "Week 14"
            - href: teaching/CIVE461/weeks/week-15.qmd
              text: "Week 15"
            - href: teaching/CIVE461/weeks/week-16.qmd
              text: "Week 16"
        - section: "Project"
          contents:
            - href: teaching/CIVE461/project/project-description.qmd
              text: "Description"
            - href: teaching/CIVE461/project/project-feedback.qmd
              text: "Feedback"
        - section: "Assignments"
          contents:
            - href: teaching/CIVE461/assignments/indiv_assignment1.qmd
              text: "Assignment 1"
            - href: teaching/CIVE461/assignments/indiv_assignment2.qmd
              text: "Assignment 2"
        - section: "Application Exercises"
          contents:
            - href: teaching/CIVE461/ae/ae-0-travel-diary.qmd
              text: "AE 0 - Travel Diary"
            - href: teaching/CIVE461/ae/ae-1-transportation-planning-experience.qmd
              text: "AE 1 - Planning Experience"
            - href: teaching/CIVE461/ae/ae-2-statistics.qmd
              text: "AE 2 - Statistics"
            - href: teaching/CIVE461/ae/ae-3-transport-plans.qmd
              text: "AE 3 - Regional Plans"
            - href: teaching/CIVE461/ae/ae-4-trip-distribution.qmd
              text: "AE 4 - Trip Distribution"
            - href: teaching/CIVE461/ae/ae-5-equity.qmd
              text: "AE 5 - Equity"
            - href: teaching/CIVE461/ae/ae-6-trip-assignment.qmd
              text: "AE 6 - Trip Assignment"
            - href: teaching/CIVE461/ae/ae-7-review.qmd
              text: "AE 7 - Review"

    - id: ENCI707
      title: "ENCI 707"
      background: "#95B0B7"
      logo: "assets/images/teaching/ENCI707/logo.png"
      logo-href: "/teaching/ENCI707/"
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: teaching/ENCI707/course-overview.qmd
              text: Overview
            - href: teaching/ENCI707/course-syllabus.qmd
              text: Syllabus
            - href: teaching/ENCI707/course-team.qmd
              text: "Teaching team"
            - href: teaching/ENCI707/index.qmd
              text: Schedule
            - href: teaching/ENCI707/course-faq.qmd
              text: FAQ
            - href: teaching/ENCI707/computing-access.qmd
              text: "Computing Access"
        - section: "Weekly Materials"
          contents:
            - href: teaching/ENCI707/weeks/week-1.qmd
              text: "Week 1"
            - href: teaching/ENCI707/weeks/week-2.qmd
              text: "Week 2"
            - href: teaching/ENCI707/weeks/week-3.qmd
              text: "Week 3"
            - href: teaching/ENCI707/weeks/week-4.qmd
              text: "Week 4"
            - href: teaching/ENCI707/weeks/week-5.qmd
              text: "Week 5"
            - href: teaching/ENCI707/weeks/week-6.qmd
              text: "Week 6"
            - href: teaching/ENCI707/weeks/week-7.qmd
              text: "Week 7"
            - href: teaching/ENCI707/weeks/week-8.qmd
              text: "Week 8"
            - href: teaching/ENCI707/weeks/week-9.qmd
              text: "Week 9"
            - href: teaching/ENCI707/weeks/week-10.qmd
              text: "Week 10"
            - href: teaching/ENCI707/weeks/week-11.qmd
              text: "Week 11"
            - href: teaching/ENCI707/weeks/week-12.qmd
              text: "Week 12"
            - href: teaching/ENCI707/weeks/week-13.qmd
              text: "Week 13"
            - href: teaching/ENCI707/weeks/week-14.qmd
              text: "Week 14"
        - section: "Project"
          contents:
            - href: teaching/ENCI707/project/project-description.qmd
              text: "Description"
            - href: teaching/ENCI707/project/data-sets.qmd
              text: "Data sources"
        - section: "Assignments"
          contents:
            - href: teaching/ENCI707/assignments/assignment-1.qmd
              text: "Assignment 1"
            - href: teaching/ENCI707/assignments/assignment-2.qmd
              text: "Assignment 2"
            - href: teaching/ENCI707/assignments/assignment-3.qmd
              text: "Assignment 3"
        - section: "Application Exercises"
          contents:
            - href: teaching/ENCI707/ae/ae-1.qmd
              text: "AE 1 - Demand Analysis"
            - href: teaching/ENCI707/ae/ae-2.qmd
              text: "AE 2 - Ecological Economics"
            - href: teaching/ENCI707/ae/ae-3.qmd
              text: "AE 3 - Surveys"
            - href: teaching/ENCI707/ae/ae-4.qmd
              text: "AE 4 - Statistics Activity"
            - href: teaching/ENCI707/ae/ae-5.qmd
              text: "AE 5 - Policy Case Study I"
            - href: teaching/ENCI707/ae/ae-6.qmd
              text: "AE 6 - Policy Case Study II"
            - href: teaching/ENCI707/ae/ae-7.qmd
              text: "AE 7 - Computing Visuals"
            - href: teaching/ENCI707/ae/ae-8.qmd
              text: "AE 8 - Computing Models"
            - href: teaching/ENCI707/ae/ae-9.qmd
              text: "AE 8 - Disaggregate Demand"

    - id: vehicle_adoption
      style: "docked"
      search: true
      align: center
      contents:
        - section: "EV"
          contents:
            - href: projects/ev_adoption/ev.qmd
              text: EV Adoption Graphs
    - id: shared_mobility
      style: "docked"
      search: true
      align: center        
      contents:
        - section: "Bikeshare"
          contents:
            - href: projects/bikeshare/Omaha.qmd
              text: Omaha Bikeshare
            - href: projects/bikeshare/Lincoln.qmd
              text: Lincoln Bikeshare
            - href: projects/bikeshare/Clustering.qmd
              text: Bikeshare Clustering
    - id: infrastructure_finance
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Transportation Finance in Canada"
          contents:
            - href: projects/transport_canada/transport_canada.qmd
              text: Transportation Finance in Canada
            - href: projects/transport_canada/carbon_pricing.html
              text: Carbon Pricing
    - id: Books
      style: "docked"
      search: true
      align: center
      contents:
        - href: misc/books.qmd
          text: Books

    - id: Teaching
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Teaching"
          contents:
            - href: teaching/CIVE461/index.qmd
              text: CIVE461
            - href: teaching/ENCI707/index.qmd
              text: ENCI707

  page-footer:
    left: |
      Developed by Hawkinslab
    # center:
    #   - text: "About"
    #     href: about.qmd
      # - text: "FAQ"
      #   href: docs/faq/index.qmd
      # - text: "License"
      #   href: license.qmd
      # - text: "Trademark"
      #   href: trademark.qmd
      
    right:
      - icon: github
        href: https://github.com/UNL-Hawkins-Lab/Hawkinslab
        aria-label: Quarto GitHub     
    background: "#595758"
    
format:
  html:
    theme: 
      - yeti
      - styles/custom.scss
    # css: styles.css
    toc: true
    link-external-newwindow: false
    grid:
      margin-width: 500px